---
title: "ProyectoAED2023"
author: "Samuel Ortega & Javier Hinarejos"
date: "2023-10-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
rm(list = ls())
```

Cargar datos a R.

```{r}
data_file <- "./data/md_EVR_2021.txt"
raw_data <- readLines(data_file, encoding = "UTF-8")

excel_file_path <- "./data/dr_EVR_2021.xlsx"
main_sheet <- "Diseño"
vars_table <- read_excel(var_table_file, sheet = "Diseño", range = "A2:H19", col_names = TRUE)

sheet_names <- excel_sheets(excel_file_path)
sheet_list <- list()

for (sheet_name in sheet_names[sheet_names != "Diseño"]) {
  sheet_data <- read_excel(excel_file_path, sheet = sheet_name, col_names = FALSE)
  sheet_list[[sheet_name]] <- sheet_data
}
```

Limpiar entradas con longitud incorrecta. Eliminamos la última fila de la tabla.

```{r}
entry_length <- vars_table$Longitud[vars_table$Variable == "TOTAL"]

filtered_raw_data <- raw_data[nchar(raw_data) == entry_length]

vars_table <- vars_table[vars_table$Variable != "TOTAL", ]
```

Creamos el dataframe.

```{r}
splitted_raw_data <- list()

for (var_idx in 1:nrow(vars_table)) {
  
  aux <- substr(
    filtered_raw_data,
    vars_table$Posición[var_idx],
    vars_table$Posición[var_idx] + vars_table$Longitud[var_idx] - 1)
  
  splitted_raw_data[[vars_table$Variable[var_idx]]] <- aux
}

df <- data.frame(splitted_raw_data)
```

Leemos los diccionarios de las variables del excel y sustituimos el código por la descripción.

```{r}
vars_with_dict <- which(!is.na(vars_table$`Diccionario de la variable`))

for (var_idx in vars_with_dict) {
    
  # Leemos el nombre del diccionario y en que hoja está
  dict_name  <- vars_table$`Diccionario de la variable`[var_idx]
  dict_sheet <- vars_table$`Diccionario ubicado en la hoja…`[var_idx]
  
  # Cogemos la hoja y buscamos el comienzo diccionario
  aux_table <- sheet_list[[dict_sheet]]
  dict_pos <- which(aux_table == dict_name, arr.ind = TRUE)
  
  # Miramos donde acaba el diccionario
  dict_row_end <- dict_pos[1]
  while ( (dict_row_end + 1) <= nrow(aux_table) ) {
    
    if ( is.na(aux_table[[(dict_row_end + 1), dict_pos[2]]]) ) {
      break
    }
    dict_row_end <- dict_row_end + 1
  }
  
  # Creamos una tabla con el diccionario
  dict_df <- aux_table[(dict_pos[1] + 1):dict_row_end, dict_pos[2]:(dict_pos[2] + 1)]
  colnames(dict_df) <- unlist(dict_df[1, ])
  dict_df <- dict_df[-1, ]
  
  # Sustituimos los caracteres por su valor segun el diccionario
  values <- dict_df$Descripción[match(df[[vars_table$Variable[var_idx]]], dict_df$Código)]
  df[vars_table$Variable[var_idx]] <- values
  
}
```

